version: 2.1

jobs:
  bumpversion:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: bumpversion
          command: |
            apt-get update
            apt-get install -y git
            git config --global user.email "circlecistuff@todandlorna.com"
            git config --global user.name "Runner"
            git fetch origin
            git checkout -B master
            pip install bumpversion
            bumpversion patch --verbose  # bumpversion installed in runner
            git push origin master --tags

  publish_image:
    environment:
      VERSION: 0.0.25
      TAG: tnlcommunity/tnl-runner-image:0.0.25
      TAG_LATEST: tnlcommunity/tnl-runner-image:latest
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: bumpversion
          command: |
            apt-get update -y && apt-get install -y docker-ce
            docker login -u ${HUB_USERNAME} -p ${HUB_TOKEN} ${REPO}
            docker build . -t ${TAG}
            docker tag ${TAG} ${TAG_LATEST}
            docker push ${TAG}
            docker push ${TAG_LATEST}

workflows:
  version: 2
  bumpversion:
    jobs:
      - bumpversion:
          filters:
            branches:
              only:
                - master
  publish_image:
    jobs:
      - publish_image: 
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/